language: node_js
node_js:
  - "7.1"
sudo: false
os: osx
install:
  - rm -rf node_modules/
  - npm install
script:
  - npm build
  - npm test
  - npm run build:ios
  - xcodebuild clean -project ios/Passman.xcodeproj -configuration Release -alltargets
  - xcodebuild -project ios/Passman.xcodeproj -configuration Release -scheme Passman -archivePath ios/build/Passman.xcarchive
# For exporting a enrolled dev-account will be needed therefore archiving makes no sense
#  - xcodebuild -exportArchive -archivePath ios/build/Passman.xcarchive -exportPath ios/build/Passman -exportFormat ipa
