language: node_js
node_js:
  - "8"
sudo: false
os: osx
osx_image: xcode9.4
install:
  - rm -rf node_modules/
  - npm install
script:
  - npm build
  - npm test
  - npm run build:ios
  - xcodebuild -project ios/Passman.xcodeproj -configuration Release -scheme Passman -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# For exporting a enrolled dev-account will be needed therefore archiving makes no sense
#  - xcodebuild -exportArchive -archivePath ios/build/Passman.xcarchive -exportPath ios/build/Passman -exportFormat ipa
