language: node_js
node_js:
  - "7.1"
sudo: false
os: osx
install:
  - rm -rf node_modules/
  - npm install
script:
  - npm lint
  - npm build
  - npm test
  - npm run build:ios
  - xcodebuild -project ios/Passman.xcodeproj -configuration Release -scheme Passman ios/build
